#!/bin/sh

[ -z "$1" ] && echo "usage: $0 filename" 1>&2 && exit 1
[ -z "$2" ] && NAME="$(basename "$1")" || NAME="$2"

echo -n "const unsigned char ${NAME}[]={"
od -vA n -w1 -t u1 "$1"|tr -d ' '|tr \\n ,
echo "};const unsigned long ${NAME}_size=sizeof(${NAME});"
